//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tài khoản.
        /// </summary>
        public static string AccountManager {
            get {
                return ResourceManager.GetString("AccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm quảng cáo.
        /// </summary>
        public static string Add_ADV {
            get {
                return ResourceManager.GetString("Add_ADV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị website.
        /// </summary>
        public static string AdministrationWebsite {
            get {
                return ResourceManager.GetString("AdministrationWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo cột trái.
        /// </summary>
        public static string Adv_left {
            get {
                return ResourceManager.GetString("Adv_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dưới sản phẩm nổi bật.
        /// </summary>
        public static string Adv_pro_feat {
            get {
                return ResourceManager.GetString("Adv_pro_feat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dưới sản phẩm khuyến mãi.
        /// </summary>
        public static string Adv_pro_prom {
            get {
                return ResourceManager.GetString("Adv_pro_prom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo cột phải.
        /// </summary>
        public static string Adv_right {
            get {
                return ResourceManager.GetString("Adv_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dưới slide trang chủ.
        /// </summary>
        public static string Adv_under {
            get {
                return ResourceManager.GetString("Adv_under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo.
        /// </summary>
        public static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý quảng cáo.
        /// </summary>
        public static string AdvManagement {
            get {
                return ResourceManager.GetString("AdvManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thực sự muốn xóa bản ghi nay ?.
        /// </summary>
        public static string Alert_delete {
            get {
                return ResourceManager.GetString("Alert_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string Changepassword {
            get {
                return ResourceManager.GetString("Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình tiền tệ.
        /// </summary>
        public static string Configurecurrency {
            get {
                return ResourceManager.GetString("Configurecurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình thanh toán.
        /// </summary>
        public static string Configurepayment {
            get {
                return ResourceManager.GetString("Configurepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình vận chuyển.
        /// </summary>
        public static string Configuretransport {
            get {
                return ResourceManager.GetString("Configuretransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QL Khách hàng liên hệ.
        /// </summary>
        public static string ContactCustomerManagement {
            get {
                return ResourceManager.GetString("ContactCustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng.
        /// </summary>
        public static string Customergroup {
            get {
                return ResourceManager.GetString("Customergroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý khách hàng.
        /// </summary>
        public static string Customermanagement {
            get {
                return ResourceManager.GetString("Customermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao diện.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tiêu đề.
        /// </summary>
        public static string EntryRequirementstitle {
            get {
                return ResourceManager.GetString("EntryRequirementstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được nhập tối đa 10 ký tự !.
        /// </summary>
        public static string Error_10 {
            get {
                return ResourceManager.GetString("Error_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được nhập tối đa 200 ký tự !.
        /// </summary>
        public static string Error_200 {
            get {
                return ResourceManager.GetString("Error_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được nhập tối đa 400 ký tự !.
        /// </summary>
        public static string Error_400 {
            get {
                return ResourceManager.GetString("Error_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được nhập tối đa 500 ký tự !.
        /// </summary>
        public static string Error_500 {
            get {
                return ResourceManager.GetString("Error_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập ảnh.
        /// </summary>
        public static string Error_Imageenter {
            get {
                return ResourceManager.GetString("Error_Imageenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được phếp nhập số dương.
        /// </summary>
        public static string Error_Number_positive {
            get {
                return ResourceManager.GetString("Error_Number_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần phải chọn vị trí hiển thị !.
        /// </summary>
        public static string Error_position {
            get {
                return ResourceManager.GetString("Error_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        public static string Evaluate {
            get {
                return ResourceManager.GetString("Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá sản phẩm mới.
        /// </summary>
        public static string evaluatenewproducts {
            get {
                return ResourceManager.GetString("evaluatenewproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất danh sách đơn hàng.
        /// </summary>
        public static string Exportorderslist {
            get {
                return ResourceManager.GetString("Exportorderslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu flash.
        /// </summary>
        public static string Flashtype {
            get {
                return ResourceManager.GetString("Flashtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có tất cả.
        /// </summary>
        public static string Have_everything {
            get {
                return ResourceManager.GetString("Have_everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiểu cao.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu liên kết.
        /// </summary>
        public static string Linktype {
            get {
                return ResourceManager.GetString("Linktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khách hàng liên hệ.
        /// </summary>
        public static string Listofregisteredmail {
            get {
                return ResourceManager.GetString("Listofregisteredmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đơn hàng.
        /// </summary>
        public static string Listorders {
            get {
                return ResourceManager.GetString("Listorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo đối tác.
        /// </summary>
        public static string Logo_cus {
            get {
                return ResourceManager.GetString("Logo_cus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QL Ý kiến về website.
        /// </summary>
        public static string ManagementCommentwebsite {
            get {
                return ResourceManager.GetString("ManagementCommentwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QL Nhóm tùy chọn.
        /// </summary>
        public static string ManagementGroupOptions {
            get {
                return ResourceManager.GetString("ManagementGroupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tùy chọn.
        /// </summary>
        public static string ManagementOptions {
            get {
                return ResourceManager.GetString("ManagementOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý quảng cáo.
        /// </summary>
        public static string Manager_ADV {
            get {
                return ResourceManager.GetString("Manager_ADV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QL Nhà sản xuất.
        /// </summary>
        public static string ManufacturerManagement {
            get {
                return ResourceManager.GetString("ManufacturerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin nhắn.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn từ khách hàng.
        /// </summary>
        public static string Messagesfromcustomer {
            get {
                return ResourceManager.GetString("Messagesfromcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liên hệ khách hàng mới.
        /// </summary>
        public static string newcustomercontact {
            get {
                return ResourceManager.GetString("newcustomercontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin nhắn đơn hàng mới.
        /// </summary>
        public static string Newordermessage {
            get {
                return ResourceManager.GetString("Newordermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập số từ (1-&gt;9).
        /// </summary>
        public static string Number_1_9 {
            get {
                return ResourceManager.GetString("Number_1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý khác.
        /// </summary>
        public static string Othermanagement {
            get {
                return ResourceManager.GetString("Othermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán bằng thẻ.
        /// </summary>
        public static string Paymentbycard {
            get {
                return ResourceManager.GetString("Paymentbycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán tại cửa hàng.
        /// </summary>
        public static string Paymentinshop {
            get {
                return ResourceManager.GetString("Paymentinshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán OnePay.
        /// </summary>
        public static string PaymentVisaOnePay {
            get {
                return ResourceManager.GetString("PaymentVisaOnePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí hiển thị.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỏi đáp sản phẩm.
        /// </summary>
        public static string ProductFAQs {
            get {
                return ResourceManager.GetString("ProductFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật giá sản phẩm.
        /// </summary>
        public static string Productupdateprices {
            get {
                return ResourceManager.GetString("Productupdateprices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tắt cả tin.
        /// </summary>
        public static string SeeAllMessages {
            get {
                return ResourceManager.GetString("SeeAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn vị trí.
        /// </summary>
        public static string Select_location {
            get {
                return ResourceManager.GetString("Select_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh chạy slider trang chủ.
        /// </summary>
        public static string Slide_home {
            get {
                return ResourceManager.GetString("Slide_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        public static string Statistical {
            get {
                return ResourceManager.GetString("Statistical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ trực tuyến.
        /// </summary>
        public static string SupportOnline {
            get {
                return ResourceManager.GetString("SupportOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Website.
        /// </summary>
        public static string Viewwebsite {
            get {
                return ResourceManager.GetString("Viewwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo !.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều rộng.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có.
        /// </summary>
        public static string Youhave {
            get {
                return ResourceManager.GetString("Youhave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có đơn hàng mới.
        /// </summary>
        public static string Youhavenotorder {
            get {
                return ResourceManager.GetString("Youhavenotorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có liên hệ khách hàng mới.
        /// </summary>
        public static string Younotcontact {
            get {
                return ResourceManager.GetString("Younotcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có.
        /// </summary>
        public static string YouNothave {
            get {
                return ResourceManager.GetString("YouNothave", resourceCulture);
            }
        }
    }
}
